<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

    <!--==== INERTIAL ====-->
    <xacro:include filename = '$(find amr_description)/urdf/amr_urdf/inertial.xacro'/>

    <!--==== MATERIALS ====-->
    <material name = 'white'>
        <color rgba = '1 1 1 1'/>
    </material>

    <material name = 'black'>
        <color rgba = '0 0 0 1'/>
    </material>

    <material name = 'blue'>
        <color rgba = '0 0 0.8 1'/>
    </material>

    <material name = 'red'>
        <color rgba = '0.8980392156862745 0.0 0.0 1.0'/>
    </material>

    <material name="grey">
        <color rgba="0.2 0.2 0.2 1.0"/>
      </material>
    
    <material name="green">
        <color rgba="0.0 1.0 0.0 1.0"/>
    </material>

    <material name="yellow">
        <color rgba="${255/255} ${108/255} ${10/255} 1.0"/>
    </material>


    <!--==== AMR BASE ====-->
    <xacro:property name = 'base_length' value = '0.519208'/>
    <xacro:property name = 'base_width' value = '0.559208'/> 
    <xacro:property name = 'base_height' value = '0.559208'/> 
    <xacro:property name = 'base_mass' value = '25.0'/> <!--35.0-->

    <!--==== ACTUAL WHEEL ====-->
    <xacro:property name = 'actual_wheel_length' value = '0.040205'/>
    <xacro:property name = 'actual_wheel_radius' value = '0.0625'/>
    <xacro:property name = 'actual_wheel_mass' value = '5.0'/>
    <xacro:property name = 'actual_wheel_dx' value = '0.0'/>
    <xacro:property name = 'actual_wheel_dy' value = '0.19385'/>
    <xacro:property name = 'actual_wheel_dz' value = '0.0625'/>

    <!--==== SLIDER ====-->
    <xacro:property name = 'slider_length' value = '0.774721'/>
    <xacro:property name = 'slider_width' value = '0.165472'/> 
    <xacro:property name = 'slider_height' value = '0.125472'/> 
    <xacro:property name = 'slider_mass' value = '12.0'/> <!--12.0-->
    <xacro:property name = 'slider_dx' value = '0.164'/> <!---0.1665-->
    <xacro:property name = 'slider_dy' value = '0.00034497'/>
    <xacro:property name = 'slider_dz' value = '0.1205'/>

    <!--==== CASTER BASE ====-->
    <xacro:property name = 'caster_base_length' value = '0.083707'/>
    <xacro:property name = 'caster_base_width' value = '0.083507'/>
    <xacro:property name = 'caster_base_height' value = '0.009507'/>
    <xacro:property name = 'caster_base_mass' value = '1.0'/>
    <xacro:property name = 'caster_base_dx' value = '-0.4415'/>
    <xacro:property name = 'caster_base_dy' value = '-0.00034497'/>
    <xacro:property name = 'caster_base_dz' value = '-0.0465'/>

    <!--==== CASTER SUPPORT ====-->
    <xacro:property name = 'caster_support_length' value = '0.049543'/>
    <xacro:property name = 'caster_support_radius' value = '0.032715'/>
    <xacro:property name = 'caster_support_mass' value = '1.0'/>
    <xacro:property name = 'caster_support_dx' value = '0.0'/>
    <xacro:property name = 'caster_support_dy' value = '0.0'/>
    <xacro:property name = 'caster_support_dz' value = '-0.00924'/>

    <!--==== CASTER WHEEL ====-->
    <xacro:property name = 'caster_wheel_length' value = '0.036997'/>
    <xacro:property name = 'caster_wheel_radius' value = '0.024063'/>
    <xacro:property name = 'caster_wheel_mass' value = '1.0'/>
    <xacro:property name = 'caster_wheel_dx' value = '-0.013949'/>
    <xacro:property name = 'caster_wheel_dy' value = '0.0'/>
    <xacro:property name = 'caster_wheel_dz' value = '-0.0397'/>


    <!--==== BASE LINK ====-->
    <link name = 'base_footprint'/>

    <link name = 'base_link'>
        <visual>
            <origin xyz="0.0 0.0 0.0" rpy="0 0 0"/>
            <geometry>
                <mesh filename="package://amr_description/meshes/amr_core/base_link.STL" />
            </geometry>
            <material name = 'white'/>
        </visual>

        <collision>
            <origin xyz="0 0 0.0 " rpy="0 0 0"/>
            <geometry>
                <mesh filename="package://amr_description/meshes/amr_core/base_link.STL" />
            </geometry>
        </collision>

        <xacro:inertial_box mass="${base_mass}" x="${base_length}" y="${base_width}" z="${base_height}">
            <origin xyz="0.0 0.0 ${base_height/2}" rpy="0 0 0 "/>
        </xacro:inertial_box>
    </link>

    <joint name = 'base_joint' type = 'fixed'>
        <parent link="base_footprint"/>
        <child link="base_link"/>
        <origin xyz="0 0 0" rpy="0 0 0"/>
    </joint>

    <gazebo reference="base_link"> 
        <material>Gazebo/White</material>
        <mu1>1.0</mu1>
        <mu2>1.0</mu2>
        <kp>1000000.0</kp>
        <kd>1.0</kd>
        <fdir1>.1 0 0</fdir1>
    </gazebo>


    <!--==== ACTUAL WHEEL ====-->
    <xacro:macro name="actual_wheel" params="prefix reflect">
        <link name="${prefix}_wheel_link">
            <visual>
                <origin xyz="0 0 0" rpy="0 0 0"/>
                <geometry>
                    <mesh filename="package://amr_description/meshes/amr_core/${prefix}_wheel_link.STL" />
                </geometry>
                <material name = 'yellow'/>
            </visual>

            <collision>
                <origin xyz="0 0 0" rpy="0 0 0"/>
                <geometry>
                    <sphere radius="${actual_wheel_radius}"/>
                </geometry>
            </collision>
    
            <xacro:inertial_cylinder mass="${actual_wheel_mass}" length="${actual_wheel_length}" radius="${actual_wheel_radius}">
            <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
            </xacro:inertial_cylinder>
        </link>
        
        <joint name="${prefix}_wheel_joint" type="continuous">
            <parent link="base_link"/>
            <child link="${prefix}_wheel_link"/>
            <origin xyz="${actual_wheel_dx} ${reflect * actual_wheel_dy} ${actual_wheel_dz}" rpy="0 0 0"/>
            <axis xyz="0 1 0"/>
            <limit effort="100" velocity="20.0" />
        </joint>

        <gazebo reference="${prefix}_wheel_link"> 
            <material>Gazebo/Orange</material>
            <mu1 value="250.0"/>
            <mu2 value="250.0"/>
            <kp value="100000000.0"/>
            <kd value="0.000001"/>
            <minDepth>0.00</minDepth>
        </gazebo>
    </xacro:macro>
    <xacro:actual_wheel prefix="left" reflect="1"/>
    <xacro:actual_wheel prefix="right" reflect="-1"/>


    <!--==== SLIDER LINK ====-->
    <link name = 'slider_link'>
        <visual>
            <origin xyz="0.0 0.0 0.0" rpy="0 0 0"/>
            <geometry>
                <mesh filename="package://amr_description/meshes/amr_core/slider_link.STL" />
            </geometry>
            <material name = 'white'/>
        </visual>

        <collision>
            <origin xyz="0 0 0.0 " rpy="0 0 0"/>
            <geometry>
                <mesh filename="package://amr_description/meshes/amr_core/slider_link.STL" />
            </geometry>
        </collision>

        <xacro:inertial_box mass="${slider_mass}" x="${slider_length}" y="${slider_width}" z="${slider_height}">
            <origin xyz="${caster_base_dx} 0.0 0.0" rpy="0 0 0 "/>
        </xacro:inertial_box>
    </link>

    <joint name = 'slider_joint' type = 'prismatic'>
    <!-- <joint name = 'slider_joint' type = 'fixed'> -->
        <parent link="base_link"/>
        <child link="slider_link"/>
        <origin xyz="${slider_dx} ${slider_dy} ${slider_dz}" rpy="0 0 0"/>
        <limit effort="100.0" lower="-0.3445" upper="0.0" velocity="0.5"/>
        <axis xyz="1 0 0"/>
        <dynamics damping="100.0"/>
    </joint>

    <gazebo reference="slider_link"> 
        <material>Gazebo/White</material>
        <mu1>200.0</mu1>
        <mu2>200.0</mu2>
        <kp>1000000.0</kp>
        <kd>1.0</kd>
        <fdir1>.1 0 0</fdir1>
    </gazebo>


    <!--==== CASTER BASE ====-->
    <link name="caster_base_link">
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <mesh filename="package://amr_description/meshes/amr_core/caster_base_link.STL"/>
            </geometry>
            <material name = 'white'/>
        </visual>

        <collision>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <mesh filename="package://amr_description/meshes/amr_core/caster_base_link.STL"/>
            </geometry>
        </collision>

        <xacro:inertial_box mass="${caster_base_mass}" x="${caster_base_length}" y="${caster_base_width}" z="${caster_base_height}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_box>
    </link>

    <joint name = 'caster_base_joint' type = 'fixed'>
        <parent link = "slider_link"/>
        <child link = 'caster_base_link'/>
        <origin xyz="${caster_base_dx} ${caster_base_dy} ${caster_base_dz}" rpy="0 0 0"/>
        <axis xyz="0 0 0"/>
    </joint>

    <gazebo reference="caster_base_link"> 
        <material>Gazebo/White</material>
        <!-- <kp>10000.0</kp>
        <kd>1.0</kd> -->
    </gazebo>


    <!--==== CASTER SUPPORT ====-->
    <link name="caster_support_link">
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <mesh filename="package://amr_description/meshes/amr_core/caster_support_link.stl"/>
            </geometry>
            <material name = 'white'/>
        </visual>

        <collision>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <mesh filename="package://amr_description/meshes/amr_core/caster_support_link.stl"/>
            </geometry>
        </collision>

        <xacro:inertial_cylinder mass="${caster_support_mass}" length="${caster_support_length}" radius="${caster_support_radius}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_cylinder>
    </link>

    <joint name = 'caster_support_joint' type = 'continuous'>
        <parent link = "caster_base_link"/>
        <child link = 'caster_support_link'/>
        <origin xyz="${caster_support_dx} ${caster_support_dy} ${caster_support_dz}" rpy="0 0 0"/>
        <axis xyz="0 0 1"/>
    </joint>

    <gazebo reference="caster_support_link"> 
        <material>Gazebo/White</material>
        <!-- <kp>10000.0</kp>
        <kd>1.0</kd> -->
    </gazebo>


    <!--==== CASTER WHEEL ====-->
    <link name = 'caster_wheel_link'>
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <mesh filename="package://amr_description/meshes/amr_core/caster_wheel_link.stl" />
            </geometry>
            <material name = 'grey'/>
        </visual>

        <collision>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <sphere radius="${caster_wheel_radius}"/>
            </geometry>
        </collision>

        <xacro:inertial_cylinder mass="${caster_wheel_mass}" length="${caster_wheel_length}" radius="${caster_wheel_radius}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_cylinder>
    </link>

    <joint name = 'caster_wheel_joint' type = 'continuous'>
        <parent link = 'caster_support_link'/>
        <child link = 'caster_wheel_link'/>
        <origin xyz="${caster_wheel_dx} ${caster_wheel_dy} ${caster_wheel_dz}" rpy="0 0 0"/>
        <axis xyz="0 1 0"/>
    </joint>

    <gazebo reference="caster_wheel_link">
        <material>Gazebo/Grey</material>
        <mu1 value="150.0"/>
        <mu2 value="150.0"/>
        <kp value="10000000.0"/>
        <kd value="0.00001"/>
        <minDepth>0.00</minDepth>
    </gazebo>
</robot>