scan_filter_chain:
- name: back_scanner_filter
  type: laser_filters/LaserScanPolygonFilter
  params:
    polygon_frame: back_laser_link
    polygon: [[-0.05, -0.75], [-0.05, 0.75], [2.0, 0.75], [2.0, -0.75]]
    invert: true
