scan_filter_chain:
- name: front_scanner_filter
  type: laser_filters/LaserScanPolygonFilter
  params:
    polygon_frame: front_laser_link
    polygon: [[-0.05, -0.75], [-0.05, 0.75], [3.0, 0.75], [3.0, -0.75]]
    invert: true
