diff_drive_controller:
  type        : "diff_drive_controller/DiffDriveController"
  left_wheel  : 'left_wheel_joint'
  right_wheel : 'right_wheel_joint'
  publish_rate: 50.0               # default: 50
  pose_covariance_diagonal : [0.00001, 0.00001, 1000000.0, 1000000.0, 1000000.0, 1000.0]
  twist_covariance_diagonal: [0.1, 0.1, 1000000.0, 1000000.0, 1000000.0, 1000.0]
  enable_odom_tf: false

  # Wheel separation and diameter. These are both optional.
  # diff_drive_controller will attempt to read either one or both from the
  # URDF if not specified as a parameter
  wheel_separation : 0.3877
  wheel_radius : 0.0625

  # Wheel separation and radius multipliers
  wheel_separation_multiplier: 1.0 # default: 1.0
  wheel_radius_multiplier    : 1.0 # default: 1.0

  # Velocity commands timeout [s], default 0.5
  cmd_vel_timeout: 0.5

  # Publish the velocity command to be executed. 
  # It is to monitor the effect of limiters on the controller input.
  publish_speed_cmd: false

  # Base frame_id
  base_frame_id: base_footprint
  odom_frame_id: odom

  # Velocity and acceleration limits
  # Whenever a min_* is unspecified, default to -max_*
  linear:
    x:
      has_velocity_limits    : true
      max_velocity           : 1.0  # m/s
      has_acceleration_limits: true
      max_acceleration       : 2.0  # m/s^2

  angular:
    z:
      has_velocity_limits    : true
      max_velocity           : 1.5  # rad/s; move_base max_rot_vel: 1.0
      has_acceleration_limits: true
      max_acceleration       : 2.5  # rad/s^2; move_base acc_lim_th: 2.0