# -----------------------------------

hardware_interface:
  joints:
    - left_wheel_joint
    - right_wheel_joint
    - slider_joint

mobile_base_controller:
  type        : "diff_drive_controller/DiffDriveController"
  left_wheel  : 'left_wheel_joint'
  right_wheel : 'right_wheel_joint'
  publish_rate: 50              # this is what the real MiR platform publishes (default: 50)
  # These covariances are exactly what the real MiR platform publishes
  pose_covariance_diagonal : [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 1000.0]
  twist_covariance_diagonal: [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 1000.0]
  # pose_covariance_diagonal : [0.00001, 0.00001, 1000000.0, 1000000.0, 1000000.0, 1000.0]
  # twist_covariance_diagonal: [0.1, 0.1, 1000000.0, 1000000.0, 1000000.0, 1000.0]
  enable_odom_tf: false

  # Wheel separation and diameter. These are both optional.
  # diff_drive_controller will attempt to read either one or both from the
  # URDF if not specified as a parameter
  wheel_separation : 0.3877
  wheel_radius : 0.0625

  # Wheel separation and radius multipliers
  wheel_separation_multiplier: 1.0 # default: 1.0
  wheel_radius_multiplier    : 1.0 # default: 1.0

  # Velocity commands timeout [s], default 0.5
  cmd_vel_timeout: 0.5

  # frame_ids (same as real MiR platform)
  base_frame_id: base_footprint # default: base_link  base_footprint
  odom_frame_id: odom           # default: odom

  # Velocity and acceleration limits
  # Whenever a min_* is unspecified, default to -max_*
  linear:
    x:
      # has_velocity_limits    : true
      # max_velocity           : 1.0  # m/s; move_base max_vel_x: 0.8
      # has_acceleration_limits: true
      # max_acceleration       : 2.0  # m/s^2; move_base acc_lim_x: 1.5
      has_velocity_limits    : true
      max_velocity           : 1.0  # m/s
      # min_velocity           : -0.5 # m/s
      has_acceleration_limits: true
      max_acceleration       : 2.0  # m/s^2
      # min_acceleration       : -0.4 # m/s^2
      # has_jerk_limits        : true
      # max_jerk               : 5.0  # m/s^3

  angular:
    z:
      has_velocity_limits    : true
      max_velocity           : 1.0  # rad/s; move_base max_rot_vel: 1.0
      has_acceleration_limits: true
      max_acceleration       : 2.5  # rad/s^2; move_base acc_lim_th: 2.0
      # has_jerk_limits        : true
      # max_jerk               : 2.5  # rad/s^3

# joint_limits:
#   slider_joint:
#     has_position_limits: true
#     min_position: -0.3445
#     max_position: 0.0
#     has_velocity_limits: true
#     max_velocity: 0.05
#     # has_acceleration_limits: true
#     # max_acceleration: 5.0
#     # has_jerk_limits: true
#     # max_jerk: 100.0
#     # has_effort_limits: true
#     # max_effort: 5.0

